using System;

[Flags]
public enum DistrictState
{
    kDISTRICT_STATE_DISCONNECTED = 0,
    kDISTRICT_STATE_WORLDSERVER_LISTENING = 1,
    kDISTRICT_STATE_WORLDSERVER_CONNECT_IN_PROGRESS = 2,
    kDISTRICT_STATE_WORLDSERVER_CONNECT_COMPLETE = 3,
    kDISTRICT_STATE_WORLDSERVER_DEV_ATTACH_IN_PROGRESS = 4,
    kDISTRICT_STATE_WORLDSERVER_DEV_ATTACH_COMPLETE = 5,
    kDISTRICT_STATE_WORLDSERVER_ATTACH_IN_PROGRESS = 6,
    kDISTRICT_STATE_WORLDSERVER_ATTACH_COMPLETE = 7,
    kDISTRICT_STATE_MAX = 8
};